all: verify

# assuming share/steel/examples/pulse
STEEL_HOME ?= ../../../../..

FSTAR_OPTIONS = --include $(STEEL_HOME)/lib/steel/pulse --include ../dice/lib

COMPAT_INDEXED_EFFECTS=

include $(STEEL_HOME)/share/steel/Makefile.include
